### ISSUE TITLE
Some warnings from Android Studio maybe need te be fixed

### ISSUE THREAD

**Issue by utzcoz** [techyourchance/idocare-android#1]
Hi Vasiliy,
When I tried to view the `idocare-android` code to study `mvc/mvp` implementation discussed by your blog, I found some `Android Studio`warnings for code, which I think they maybe to be fixed. Below is the warnings list:

1. `app/src/main/java/il/co/idocare/controllers/activities/StartupActivity.java`

In `onResume` method of `StartupActivity.java`, there is a `AsyncTask` to do a wait work. But it just use java's not static anonymous class, which will holds a `this` reference of outer class which is `StartupActivity.java`. It has a memory leak risk, the `Android Studio` recommends to use let your `AsyncTask` to be static to fix its problem, which is common used to fix `Handler` memory leak problem, which is caused by the same reason. 

2. `app/src/main/java/il/co/idocare/utils/UtilMethods.java`

In `formatDate` method of `UtilMethods.java` use `SimpleDateFormat` without `Locale` to format date. But `Android Studio` recommends to use `SimpleDateFormat` with `Locale` to avoid timezone problem. Maybe `Locale.getDefault()` is a simple but useful for this warning.

3. `app/src/main/java/il/co/idocare/widgets/SwipeImageGalleryView.java`

In `SwipeImageGalleryView.java`, you overrides a constructor which is only available from `LOLLIPOP`, but your project's min sdk version is `16`.
```
public SwipeImageGalleryView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
        init();
}
```
Maybe it should be deleted , or update the min sdk or other useful method.

Above are `Android Studio` warnings , and I think they are important. 
Lastly, thanks for your awesome project, which is a wonderful mvc/mvp material.

**Comment by techyourchance** [comment]
Hi @utzcoz,
First of all - thanks a lot for the warm words, and, especially, for taking time for providing the feedback. I fixed the issues that you mentioned.

Some thoughts:

1. I'm not sure that I agree with AS recommendation here. Memory leak will happen only if the AsyncTask is not finished for some reason, which I think is not the case here. Furthermore, I think that statics should be avoided in general. In any case, I don't use AsyncTask's anymore. All my threading is done through two "poster" classes, which are also unit-testable. I refactored the implementation of SplashActivity. Also noticed few small bugs in the code, so fixed them too.

2. Added the solution you suggested.

3. This is alright because this constructor can't be called on any version prior to Lollipop. I added a special annotation that silences this warning.

Since you have already invested the time to go through the code, I suggest that you take a look at BackgroundThreadPoster and MainThreadPoster classes. I use them for multithreading, and they even have test-doubles that allow for unit-testing of multithreaded code. 

Let me know if you need more info.

Once again - thanks for heads up!

**Comment by utzcoz** [comment]
Thanks @techyourchance ,  I will invest the `BackgroundThreadPoster` and `MainThreadPoster` to get more information. Thanks for your bright reply.
